# Generated by Django 5.0.2 on 2024-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ca", "0041_remove_certificateauthority_crl_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificateauthority",
            name="private_key_path",
        ),
        migrations.AddField(
            model_name="certificateauthority",
            name="secrets",
            field=models.JSONField(default={}),
        ),
    ]
